# Uncomment this line to define a global platform for your project
# platform :ios, '7.0'

target "BJRadialMenuExample" do
  pod "BJRadialMenu", :path => "../"
  pod "POP+MCAnimate", "~> 1.0"
  pod "Tweaks", "~> 1.1.0"
  pod "UIColor+MLPFlatColors", "~> 1.0"
  pod "UIColor-CrossFade", "~> 1.1.0"


end

# Uncomment the following lines to add testing dependencies
# target "DemoTests" do
#   pod 'Expecta'
# end

